# Cvičení 1 - Půlmaraton

In [14]:
import pandas as pd

data = pd.read_csv("half_marathon.csv")
data.head()

            Jmeno  Rocnik       Cas  Rok zavodu
0  Aster Vladimír    1965  01:53:25        2019
1  Aster Vladimír    1965  02:00:19        2020
2   Asterová Jana    1974  02:16:59        2019
3   Asterová Jana    1974  02:30:01        2020
4   Baborová Anna    1990  01:58:20        2019

In [15]:
data["Cas"] = pd.to_timedelta(data["Cas"])
data["Cas 2019"] = data["Cas"].shift(1)
data = data[data["Rok zavodu"] == 2020]
data["Zmena"] = data["Cas"] - data["Cas 2019"]
data

,Jmeno,Rocnik,Cas,Rok zavodu,Cas 2019,Zmena
1,Aster Vladimír,1965,0 days 02:00:19,2020,0 days 01:53:25,0 days 00:06:54
3,Asterová Jana,1974,0 days 02:30:01,2020,0 days 02:16:59,0 days 00:13:02
5,Baborová Anna,1990,0 days 01:52:25,2020,0 days 01:58:20,-1 days +23:54:05
7,Bambas Jan,1975,0 days 02:35:39,2020,0 days 02:02:59,0 days 00:32:40
9,Barochovská Andrea,1976,0 days 02:50:05,2020,0 days 03:01:25,-1 days +23:48:40
...,...,...,...,...,...,...
180,Šulcová Jitka,1974,0 days 01:59:07,2020,0 days 01:43:12,0 days 00:15:55
182,Švarcová Petra,1974,0 days 02:50:01,2020,0 days 02:27:45,0 days 00:22:16
184,Švelch Rosťa,1966,0 days 01:55:11,2020,0 days 01:54:58,0 days 00:00:13
186,Žitková Jana,1974,0 days 02:42:48,2020,0 days 02:45:54,-1 days +23:56:54
188,Žákovec Pavel,1966,0 days 02:07:37,2020,0 days 02:03:36,0 days 00:04:01

In [4]:
data["Zmena"].mean()

Timedelta('0 days 00:09:36.031578947')

In [ ]:
bins = [-float("inf"), 0, float("inf")]
labels = ["lepší než 2019", "horší než 2019"]
zavod['Porovnání 2019 a 2020'] = pd.cut(zavod["2020-2019"], bins=bins, labels=labels)

zavod